# Includes all common properties irrespective of any environment
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
# https://docs.aws.amazon.com/sdk-for-go/api/aws/ec2metadata/
# environment variable AWS_EC2_METADATA_DISABLED=true
# instructs the SDK to disable the EC2 Metadata client
# cloud.aws.disableEc2Metadata=true (should work once SDK v2 is used by spring-cloud-starter-aws)

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 4
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        show_sql: false
        use_sql_comments: false
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  liquibase:
    parameters:
      textColumnType: TEXT
    contexts: prod
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000
  main:
    allow-bean-definition-overriding: true
---
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    httptrace:
      enabled: true
  trace:
    http:
      include:
        - REQUEST_HEADERS
        - RESPONSE_HEADERS
        - COOKIE_HEADERS
        - REMOTE_ADDRESS
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/v1/boilerplate/actuator
---
springdoc:
  show-actuator: true
---
#i18n settings start here
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

supportedLocales:
  - en_US
  - es
  - fr
#i18n settings end here
---
sort:
  user:
    default-param: firstName
    params:
      - firstName
      - lastName
      - email
---
boilerplate:
  cors:
    allowed-origins: "*"