# Includes enviornment specific properties.
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:13306/springboot-boilerplate?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 2
        max-page-size: 5